### ISSUE TITLE
UI Wireframes, Component Design

### ISSUE THREAD

**Issue by laurencecnerual** [greenfield-hippos/frontend#3]

**Comment by vicentbe10** [comment]
As I was mentioning I did some tinkering with Balsamiq wireframes tool.
https://balsamiq.com/wireframes/

If you are interested, you can pass me your emails and I will share with you the link later on.
![Image](https://github.com/user-attachments/assets/328e6ccd-7984-4bd7-a2e5-32d635f4a422)

**Comment by laurencecnerual** [comment]
For me, please try sharing to agina2@tcnj.edu

**Comment by vicentbe10** [comment]
For the desktop thinking about something like this
![Image](https://github.com/user-attachments/assets/792a76a7-0ba4-4400-afda-c9018bef32f7)

So maybe the components could be:

**Sidebar-content-list component**
- Search bar
- Content array -> Whatever is conversations of favorites

**Conversation component**
- Message array -> Containing all the messages of the conversation
- Selected conversation -> Which conversation is selected
- Is conversation selected -> Are we displaying Conversations or Favorites

**Favorite component**
- Favorite array -> Containing all the favorited messages
- Selected favorite
- Is favorite component selected

**Main display component**
- Conversation or Favorite selected
- Content array of Conversation or single Favorite message

**Comment by vicentbe10** [comment]
And maybe something like this in mobile.
![Image](https://github.com/user-attachments/assets/44a9102a-9c2d-4cee-b30b-8336a23b1ffb)

**Comment by ConwayDecker** [comment]
🥇
